
export const Producer = (data:any) => {
  return ({
    surName: data?.surname,
    firstName: data?.firstname,
    lastName: "",
    substansiveRank: "",
    phoneNumber: data?.telephoneno,
    email: "",
    sex: data?.gender === "m" ? 1 : 2,
    stateOfOrigin: "",
    localGovernmentArea: "",
    dateOfBirth: data?.birthdate,
    dateOfEnlistment: "",
    rankOnEnlistment: "",
    datePromotedToSubstantiveRank: "",
    presentComand: "",
    dateTransferedToPresentComand: "",
    dateCallToBar: "",
    discipline: "",
    generalDutyOrSpecialist: "",
    scondarySchool: "",
    apNumber: "",
    nin: data?.nin,
    employerCode: "",
    profilePhotoNin: data?.photo,
    profilePhoto: "",
    ssce: [],
    tertiary: [],
    profession: [],
    seminar: [],
    workshop: [],
    conference: [],
    service: [],
    workTransfer: [],
    lawyer: [],
    promotion: [],
    actingCapacity: "",
    deptZoneCommand: "",
    anyInstitution: ""
  });
}
